config/routes.rb
Rails.application.routes.draw do

  resources :medications
  devise_for :users

  get "welcome/index"

  get "welcome/about"

  root 'welcome#index'

  resources :users, only: :show do
    resources :medications, only: [:create, :edit, :destroy, :update, :new]
    resources :migraines, only: [:create, :destroy, :new] do
      resources :surveys, only: [:create, :destroy, :new]
    end
  end
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  belongs_to :user
end

app/models/migraine.rb
class Migraine < ActiveRecord::Base
  belongs_to :user
  has_many :surveys
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  belongs_to :migraine
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :validate_username
  has_many :medications
  has_many :migraines
  has_many :surveys


    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        if conditions[:username].nil?
          where(conditions).first
        else
          where(username: conditions[:username]).first
        end
      end
    end

     def validate_username
       if User.where(email: username).exists?
         errors.add(:username, :invalid)
       end
     end

     def login=(login)
       @login = login
     end

     def login
       @login || self.username || self.email
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
end

app/controllers/medications_controller.rb
class MedicationsController < ApplicationController
 before_action :authenticate_user!

  def show
    @medication = Medication.find(params[:id])
  end

  def new
     @user = User.find(current_user.id)
     @medication = Medication.new
   end

   def create
     @user = User.find(current_user.id)
     @medication = @user.medications.build(medication_params)
     @medication.user = current_user

     if @medication.save
       flash[:notice] = "Medication was saved."
       redirect_to user_path(current_user.id)
     else
       flash.now[:alert] = "There was an error saving the medication. Please try again."
       render :new
     end
   end

   def edit
     @medication = Medication.find(params[:id])
   end

   def update
     @medication = Medication.find(params[:id])
     @medication.assign_attributes(medication_params)

     if @medication.save
       flash[:notice] = "Medication was updated."
       redirect_to user_path
     else
       flash.now[:alert] = "There was an error saving the medication. Please try again."
       render :edit
     end
   end

   def destroy
     @medication = Medication.find(params[:id])

     if @medication.destroy
       flash[:notice] = "#{@medication.name} was deleted successfully."
        redirect_to user_path
     else
       flash.now[:alert] = "There was an error deleting the medication."
        redirect_to user_path
     end
   end


   private

   def medication_params
     params.require(:medication).permit(:user_id, :dosage_amount, :dosage_measurement, :frequency_amount, :frequency_measurement, :name)
   end

 end

app/controllers/migraines_controller.rb
class MigrainesController < ApplicationController

  def new
    @user = User.find(current_user.id)
    @migraine = Migraine.new
  end

  def create
    @user = User.find(current_user.id)
    @migraine = @user.migraines.build(migraine_params)
    @migraine.user = current_user

    if @migraine.save && @migraine.intensity >= 7
      flash[:notice] = "Because your migraine was a 7 or higher, we ask that you complete a survey that may help with your pain."
      redirect_to new_user_migraine_survey_path(current_user.id, @migraine.id)
    elsif @migraine.save && @migraine.intensity < 7
      flash[:notice] = "Migraine was saved."
      redirect_to user_path(current_user.id)
    else
      flash.now[:alert] = "There was an error saving the migraine. Please try again."
      render :new
    end
  end

  def destroy
    @migraine = Migraine.find(params[:id])

    if @migraine.destroy
      flash[:notice] = "Migraine that happened at #{@migraine.occurrence_time} was deleted successfully."
       redirect_to user_path
    else
      flash.now[:alert] = "There was an error deleting the migraine."
       redirect_to user_path
    end
  end

  private

  def migraine_params
    params.require(:migraine).permit(:user_id, :intensity, :occurrence_time)
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def new
    @user = current_user
    @migraine = Migraine.find(params[:migraine_id])
    @survey = Survey.new
  end

  def create
    @migraine = Migraine.find(params[:migraine_id])
    @survey = @migraine.surveys.build(survey_params)

    if @survey.save
      # @survey.save && @survey.food.downcase = "no"
      # flash[:alert] = "Better grab some grub!"
      flash[:notice] = "Survey was saved."
      redirect_to user_path(current_user.id)
    # elsif @survey.save && @survey.water
    # elsif @survey.save
    else
      flash.now[:alert] = "There was an error saving the survey. Please try again."
      render :new
    end
  end

  def destroy
    @survey = Survey.find(params[:id])

    if @survey.destroy
      flash[:notice] = "Survey that happened at #{@survey.occurrence_time} was deleted successfully."
       redirect_to migraine_path
    else
      flash.now[:alert] = "There was an error deleting the survey."
       redirect_to migraine_path
    end
  end

  private

  def survey_params
    params.require(:survey).permit(:migraine_id, :food, :water, :caffeine)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!

   def show
    @user = User.find(current_user.id)
    @medications = @user.medications
    @migraines = @user.migraines
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medications_helper.rb
module MedicationsHelper
end

app/helpers/migraines_helper.rb
module MigrainesHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Migraine Tracker</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
       <ul class="nav nav-tabs">
         <% if user_signed_in? %>
           <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
           <li><%= link_to "Home", welcome_index_path %></li>
           <li><%= link_to "About", welcome_about_path %></li>
           <li><%= link_to "Medications & Migraines", user_path(current_user.id) %></li>
           <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
           <li><p class="navbar-text navbar-right">Signed in as: <strong><%= current_user.email %></strong></p></li>
         <% else %>
           <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
           <li><%= link_to "Log in", new_user_session_path, :class => 'navbar-link'  %></li>
           <li><%= link_to "Home", welcome_index_path %></li>
           <li><%= link_to "About", welcome_about_path %></li>
         <% end %>
       </ul>
    </div>
  </nav>
  <div class="container">

  <div class="flash">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dimsiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
   </div>
    <%= yield %>
  </div>

</body>
</html>

app/views/medications/_form.html.erb
<%= form_for(@medication) do |f| %>
  <% if @medication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medication.errors.count, "error") %> prohibited this medication from being saved:</h2>

      <ul>
      <% @medication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%=f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter medication name!" %>
  </div>
  <div class="form-group">
    <%= f.label :dosage_amount %>
    <%= f.number_field :dosage_amount, class: 'form-control', placeholder: "Enter dosage amount!" %>
  </div>
  <div class="form-group">
    <%= f.label :dosage_measurement %>
    <%= f.select(:dosage_measurement, options_for_select([['mg', 'mg'], ['ml', 'ml']])) %>
  </div>
  <div class="form-group">
    <%= f.label :frequency_amount %>
    <%= f.text_field :frequency_amount, class: 'form-control', placeholder: "Enter your frequency here! Ex) 2 pills" %>
  </div>
  <div class="form-group">
    <%= f.label :frequency_measurement %>
    <%= f.select(:frequency_measurement, options_for_select([['every four hours', 'every four hours'], ['every six hours', 'every six hours'], ['every eight hours', 'every eight hours'], ['every twelve hours', 'every twelve hours'], ['per day', 'per day'], ['per week', 'per week'], ['per month', 'per month'], ['every three months', 'every three months'], ['at night', 'at night'], ['in the morning', 'in the morning']])) %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medications/_medication.html.erb
<%= content_tag :tr, class: "info", id: "medication-#{medication.id}" do %>
  <td><%= medication.name %></td>
  <td> <%= medication.dosage_amount %> </td>
  <td> <%= medication.dosage_measurement %> </td>
  <td> <%= medication.frequency_amount %> </td>
  <td> <%= medication.frequency_measurement %> </td>
  <td><%= link_to 'Show all', medication_path(medication) %></td>
  <td><%= link_to 'Edit', edit_medication_path(medication)%></td>
  <td><%= link_to 'Delete', [current_user, medication], method: :delete %></td>
<% end %>

app/views/medications/edit.html.erb
<h1>Edit Medication</h1>

<%= render 'form' %>

app/views/medications/new.html.erb
<h1>New Medication</h1>

<%= render 'form' %>

app/views/medications/show.html.erb
<h1><%= @medication.name %></h1>

<%= link_to "Edit Medication", edit_medication_path, class: 'btn btn-success' %>
<%= link_to "Delete Medication", @medication, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this medication?' } %>

 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @medication.name %></p>
     <p><%= @medication.dosage_amount %> </p>
     <p><%= @medication.dosage_measurement %> </p>
     <p> <%= @medication.frequency_amount %> </p>
     <p> <%= @medication.frequency_measurement %> </p>
   </div>
 </div>

app/views/migraines/_form.html.erb
<%= form_for [@user, @migraine] do |f| %>
  <% if @migraine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@migraine.errors.count, "error") %> prohibited this migraine from being saved:</h2>

      <ul>
      <% @migraine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div> 
  <% end %>
  <div class="form-group">
    <%= f.label :intensity %>
    <%= f.number_field :intensity, class: 'form-control', placeholder: "On a scale from 1 to 10, 10 being the worse migraine you've ever had how would you rate the intensity of your migraine?" %>
  </div>
  <div class="form-group">
    <%= f.label :occurrence_time %>
    <%= f.datetime_field :occurrence_time, class: 'form-control', placeholder: "When did your migraine begin?" %>
  </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/migraines/_migraine.html.erb
<%= content_tag :tr, class: "info", id: "migraine-#{migraine.id}" do %>
  <td> <%= migraine.occurrence_time %> </td>
  <td><%= migraine.intensity %></td>
  <td><%= link_to 'Delete', [current_user, migraine], method: :delete %></td>
<% end %>

app/views/migraines/new.html.erb
<h1>New Migraine</h1>

<%= render 'form' %>

app/views/survey/_survey.html.erb
<tbody>
  <%= content_tag :tr, class: "info", id: "survey-#{survey.id}" do %>
    <td><%= survey.food %></td>
    <td> <%= survey.water %> </td>
    <td> <%= survey.caffeine %> </td>
    <td><%= link_to 'Show all', user_survey_path(survey) %></td>
  <% end %>
</tbody>

app/views/surveys/_form.html.erb
<%= form_for [@user, @migraine, @survey] do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%=f.label :food %>
    <%= f.select :food, ["yes", "no"], prompt: "Have you eaten today?" %>
  </div>
  <div class="form-group">
    <%= f.label :water %>
    <%= f.number_field :water, class: 'form-control', placeholder: "How many glasses of water have you had today?" %>
  </div>
  <div class="form-group">
    <%= f.label :caffeine %>
    <%= f.number_field :caffeine, class: 'form-control', placeholder: "How many cups of caffeine have you had today?" %>
  </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_survey.html.erb
<%= content_tag :tr, class: "info", id: "survey-#{survey.id}" do %>
  <td><%= survey.food %></td>
  <td> <%= survey.water %> </td>
  <td> <%= survey.caffeine %> </td>
  <td><%= link_to 'Delete', user_migraine_survey_path(current_user, survey.migraine, survey), method: :delete %></td>
<% end %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Medication List</h1>
<div class="table-responsive">
  <table class="table table-hover ">
    <thead>
      <tr>
        <th>Medication Name</th>
        <th>Dosage</th>
        <th> </th>
        <th>Frequency</th>
      </tr>
    </thead>
    <tbody> <%= render @medications %> </tbody>
  </table>
</div>
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <div class="media-body">
        <h4 class "media-heading">
          <%= link_to 'New', new_user_medication_path(current_user.id) %>
        </div>
      </div>
    </div>
  </div>

  <h1>Migraine Intensity List</h1>
    <div class="table-responsive">
      <table class = "table table-hover">
          <% @migraines.each do |migraine| %>
          <thead>
            <tr>
              <th>Migraine Occurrance</th>
              <th>Migraine Intensity</th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "migraines/migraine",locals: { migraine: migraine } %>
            <thead>
              <tr>
                <th>Food?</th>
                <th>Glasses of Water</th>
                <th>Cups of Caffeine</th>
              </tr>
            </thead>
            <% migraine.surveys.each do |survey| %>
              <%= render partial: "surveys/survey", locals: { survey: survey } %>
            <% end %>
          <% end %>
       </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-md-8">
        <div class="media">
          <div class="media-body">
            <h4 class "media-heading">
              <%= link_to 'New', new_user_migraine_path(current_user.id) %>
            </div>
          </div>
        </div>
      </div>

app/views/welcome/about.html.erb
<h1>About Your Migraine Tracker</h1>
<p>Created by: Katelyn Hertel</p>
<p>This website was created keeping myself and my family in mind. We are all migraine sufferers and I am hoping that this app will be useful to us and all other migraine sufferers alike!</p>
<p>Your Migraine Tracker was created using Ruby on Rails</p>

app/views/welcome/index.html.erb
<h1>Welcome to Your Migraine Tracker! Please <%= link_to "Log In!", new_user_session_path, :class => 'navbar-link'  %></h1>
<p>This is the home page for Your Migraine Tracker.</p>
<p>This site contains areas for you as a user to keep track of your migraines on a day to day basis. The information you put in will be stored in a graph so you can see your progresss.</p>
<p>There is also a place for you to keep track of your headache medications as well as weather and allergy forecasts for your zip code.</p>
<p>Using <a href ="http://www.accuweather.com/">Accuweather.com</a> you will also be able to see the migraine forecast for your area.</p>